import { 
  LayoutDashboard, 
  Rocket,
  Network, 
  ScrollText, 
  GitBranch, 
  Shield, 
  Database, 
  Palette, 
  Bot, 
  Volume2, 
  Film, 
  Package, 
  Settings,
  FileJson,
  Workflow,
  Keyboard,
  Wand2,
  Archive,
  LucideIcon 
} from 'lucide-react';
import type { SectionId, DevToolsSection } from '@/types/devtools';

export const DEVTOOLS_SECTIONS: DevToolsSection[] = [
  {
    id: 'overview',
    label: 'Overview',
    icon: LayoutDashboard,
    description: 'System status and quick stats',
    shortcut: '⌘1',
    phase: 1,
  },
  {
    id: 'apps',
    label: 'App Launcher',
    icon: Rocket,
    description: 'Jump to Echoverse apps',
    shortcut: '⌘2',
    phase: 1,
  },
  {
    id: 'audio',
    label: 'Audio',
    icon: Volume2,
    description: 'TTS, transcription, and voice controls',
    shortcut: '⌘3',
    phase: 5,
  },
  {
    id: 'video',
    label: 'Video',
    icon: Film,
    description: 'Video generation and editing pipeline',
    shortcut: '⌘4',
    phase: 6,
  },
  {
    id: 'libraries',
    label: 'Libraries',
    icon: Package,
    description: 'Asset libraries and templates',
    shortcut: '⌘5',
    phase: 4,
  },
  {
    id: 'apis',
    label: 'APIs',
    icon: Network,
    description: 'API registry and health monitoring',
    shortcut: '⌘6',
    phase: 2,
  },
  {
    id: 'agents',
    label: 'Agents',
    icon: Bot,
    description: 'AI agents and automation',
    shortcut: '⌘7',
    phase: 6,
  },
  {
    id: 'data',
    label: 'Data',
    icon: Database,
    description: 'Database and storage management',
    shortcut: '⌘8',
    phase: 3,
  },
  {
    id: 'pipeline',
    label: 'Pipeline',
    icon: GitBranch,
    description: 'Visual pipeline builder',
    shortcut: '⌘9',
    phase: 2,
  },
  {
    id: 'tokens',
    label: 'Tokens',
    icon: Palette,
    description: 'Usage tracking and credits',
    shortcut: '⌘0',
    phase: 3,
  },
  {
    id: 'logs',
    label: 'Logs',
    icon: ScrollText,
    description: 'Real-time error and event logs',
    shortcut: '⌘L',
    phase: 2,
  },
  {
    id: 'security',
    label: 'Security',
    icon: Shield,
    description: 'API keys and permissions',
    shortcut: '⌘S',
    phase: 3,
  },
  {
    id: 'content',
    label: 'Content',
    icon: FileJson,
    description: 'JSON content inspector',
    shortcut: '⌘C',
    phase: 5,
  },
  {
    id: 'flowchart',
    label: 'Flowchart',
    icon: Workflow,
    description: 'Node-graph architecture view',
    shortcut: '⌘F',
    phase: 6,
  },
  {
    id: 'shortcuts',
    label: 'Shortcuts',
    icon: Keyboard,
    description: 'Keyboard shortcuts reference',
    shortcut: '⌘/',
    phase: 10,
  },
  {
    id: 'styleguide',
    label: 'Style Guide',
    icon: Palette,
    description: 'Design tokens and patterns',
    shortcut: '⌘;',
    phase: 10,
  },
  {
    id: 'generator',
    label: 'Generator',
    icon: Wand2,
    description: 'Panel code generator',
    phase: 10,
  },
  {
    id: 'export',
    label: 'Export',
    icon: Archive,
    description: 'Export logs and data',
    phase: 10,
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: Settings,
    description: 'DevTools configuration',
    shortcut: '⌘,',
    phase: 1,
  },
];

export function getSectionById(id: SectionId): DevToolsSection | undefined {
  return DEVTOOLS_SECTIONS.find(section => section.id === id);
}

export function getSectionIcon(id: SectionId): LucideIcon | undefined {
  return getSectionById(id)?.icon;
}
